### ISSUE TITLE
Дикий таймаут при загрузке сайта

### ISSUE THREAD

**Issue by andtun** [andtun/hoROOMy#15]
Попробуй открыть horoomy.ru с нового устройства - сам всё увидишь

**Comment by AndBondStyle** [comment]
Потестил на первом iPad'е и на Sony WT19i через стандартные браузеры (сайт через эти устройства точно никогда не открывался). Время загрузки страницы - не более 7-ми секунд.

**Comment by andtun** [comment]
![Он всё же есть](https://user-images.githubusercontent.com/24493432/36077157-09e6d1a4-0f78-11e8-931e-e71e2f264f8a.png)
Более того, у Славы (инвестора) вообще вылетает *connection timeout*.

Я не знаю, чем это может быть вызвано. Это не DNS, не SSL, а бэкенд.
Пофиксить надо вне всяких спринтов и в течение недели. А то на нас злятся
