### ISSUE TITLE
Предъявы ко второму спринту + другие идеи

### ISSUE THREAD

**Issue by andtun** [andtun/hoROOMy#16]
- Кнопка должна быть **слева**, отступы - больше, а то она о самый край трётся. Сам вид кнопки тоже надо проработать, простой прямоугольник - не круто. Но об этом позже.
![image](https://user-images.githubusercontent.com/24493432/36167324-83b6c39c-1106-11e8-902d-c311a6a759bf.png)
- Где выбираем адрес - упростить жизнь (ресерч)
- Арендатор: заявки арендодателю
- Ужасно
![image](https://user-images.githubusercontent.com/24493432/36167582-717c47b4-1107-11e8-9c20-c0be5f665de6.png)
- Отправка писем через mailgun
- Если у юзера уже заполнен профиль - сразу редирект на "объекты"
- Фу
![image](https://user-images.githubusercontent.com/24493432/36170274-f8bc1e18-110f-11e8-8386-2632a4d8e390.png)
- Фу (х2)
![image](https://user-images.githubusercontent.com/24493432/36170703-2ae864f4-1111-11e8-9aa9-6361500f429d.png)
- У меня писька короче, чем этот пробел
![image](https://user-images.githubusercontent.com/24493432/36170835-a39c4d34-1111-11e8-979b-d223f156d022.png)
- Арендатор так же должен отмечать согласие о персональных данных

**Comment by AndBondStyle** [comment]
Второй пункт: Ctrl+F5
