### ISSUE TITLE
SMS

### ISSUE THREAD

**Issue by andtun** [andtun/hoROOMy#2]
**Что нужно:**
Джанго-аппка в этом же репо на нашем сервере, которая по открытию url `/sms/` выдаст html с формой ввода телефона. По нажатию `отправить` на указанный телефон должна прийти смс с текстом "привет".
Так же не забудь про исследование - 5 сервисов с выбором лучшего.

**Comment by AndBondStyle** [comment]
https://habrahabr.ru/post/47794/
