### ISSUE TITLE
Сайт не открывается со всех устройств

### ISSUE THREAD

**Issue by andtun** [andtun/hoROOMy#5]
Бывает (видимо, через публичные wifi), что пишет `невозможно установить безопасное соединение с сервером` и `this site can't be reached`. 
Догадываюсь, что если убрать приоритетный редирект на https, что-то из этого вылечится.

**Comment by AndBondStyle** [comment]
Скорее всего проблема в кривой переадресации домена. Лично у меня сайт по адресу www.horoomy.ru вообще не открывается. Принудительный редирект на https убирать нельзя ввиду соображений безопасности. В любом случае, без более подробной информации о "баге" и/или доступа к DNS записям домена я ничего не смогу сделать.

**Comment by andtun** [comment]
Что-то не работает, это да.
Можно попробовать делегировать домен на сервера стороннего dns-хостинга, к которым у нас будет доступ. Запишу и сделаю это *sometime later*.
